export function preloadCharacterAssets(scene: Phaser.Scene) {
  //Character SPRITES
  //HEAD
  //BROWN STRAIGHT
  scene.load.image(
    "character-head-human-white-brown-straight-front",
    "assets/characters/heads/brownStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-brown-straight-back",
    "assets/characters/heads/brownStraight/whiteBack.png",
  );
  scene.load.image(
    "character-head-human-white-brown-straight-right",
    "assets/characters/heads/brownStraight/whiteRight.png",
  );
  scene.load.image(
    "character-head-human-white-brown-straight-left",
    "assets/characters/heads/brownStraight/whiteLeft.png",
  );
  scene.load.image(
    "character-head-human-black-brown-straight-front",
    "assets/characters/heads/brownStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-brown-straight-back",
    "assets/characters/heads/brownStraight/blackBack.png",
  );
  scene.load.image(
    "character-head-human-black-brown-straight-right",
    "assets/characters/heads/brownStraight/blackRight.png",
  );
  scene.load.image(
    "character-head-human-black-brown-straight-left",
    "assets/characters/heads/brownStraight/blackLeft.png",
  );

  //BLACK STRAIGHT
  scene.load.image(
    "character-head-human-white-black-straight-front",
    "assets/characters/heads/blackStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-black-straight-front",
    "assets/characters/heads/blackStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-black-straight-front",
    "assets/characters/heads/blackStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-black-straight-front",
    "assets/characters/heads/blackStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-straight-front",
    "assets/characters/heads/blackStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-straight-front",
    "assets/characters/heads/blackStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-straight-front",
    "assets/characters/heads/blackStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-straight-front",
    "assets/characters/heads/blackStraight/blackFront.png",
  );

  //BLONDE STRAIGHT
  scene.load.image(
    "character-head-human-white-blonde-straight-front",
    "assets/characters/heads/blondeStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-blonde-straight-front",
    "assets/characters/heads/blondeStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-blonde-straight-front",
    "assets/characters/heads/blondeStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-blonde-straight-front",
    "assets/characters/heads/blondeStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-straight-front",
    "assets/characters/heads/blondeStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-straight-front",
    "assets/characters/heads/blondeStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-straight-front",
    "assets/characters/heads/blondeStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-straight-front",
    "assets/characters/heads/blondeStraight/blackFront.png",
  );

  //RED STRAIGHT
  scene.load.image(
    "character-head-human-white-red-straight-front",
    "assets/characters/heads/redStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-red-straight-front",
    "assets/characters/heads/redStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-red-straight-front",
    "assets/characters/heads/redStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-red-straight-front",
    "assets/characters/heads/redStraight/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-black-red-straight-front",
    "assets/characters/heads/redStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-red-straight-front",
    "assets/characters/heads/redStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-red-straight-front",
    "assets/characters/heads/redStraight/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-red-straight-front",
    "assets/characters/heads/redStraight/blackFront.png",
  );

  //BLACK CURLY
  scene.load.image(
    "character-head-human-white-black-curly-front",
    "assets/characters/heads/blackCurly/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-black-curly-front",
    "assets/characters/heads/blackCurly/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-black-curly-front",
    "assets/characters/heads/blackCurly/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-black-curly-front",
    "assets/characters/heads/blackCurly/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-curly-front",
    "assets/characters/heads/blackCurly/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-curly-front",
    "assets/characters/heads/blackCurly/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-curly-front",
    "assets/characters/heads/blackCurly/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-black-curly-front",
    "assets/characters/heads/blackCurly/blackFront.png",
  );

  //BROWN CURLY
  scene.load.image(
    "character-head-human-white-brown-curly-front",
    "assets/characters/heads/brownCurly/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-brown-curly-back",
    "assets/characters/heads/brownCurly/whiteBack.png",
  );
  scene.load.image(
    "character-head-human-white-brown-curly-right",
    "assets/characters/heads/brownCurly/whiteRight.png",
  );
  scene.load.image(
    "character-head-human-white-brown-curly-left",
    "assets/characters/heads/brownCurly/whiteLeft.png",
  );
  scene.load.image(
    "character-head-human-black-brown-curly-front",
    "assets/characters/heads/brownCurly/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-brown-curly-back",
    "assets/characters/heads/brownCurly/blackBack.png",
  );
  scene.load.image(
    "character-head-human-black-brown-curly-right",
    "assets/characters/heads/brownCurly/blackRight.png",
  );
  scene.load.image(
    "character-head-human-black-brown-curly-left",
    "assets/characters/heads/brownCurly/blackLeft.png",
  );

  //BLONDE CURLY
  scene.load.image(
    "character-head-human-white-blonde-curly-front",
    "assets/characters/heads/blondeCurly/whiteFront.png",
  );
  scene.load.image(
    "character-head-human-white-blonde-curly-back",
    "assets/characters/heads/blondeCurly/whiteBack.png",
  );
  scene.load.image(
    "character-head-human-white-blonde-curly-right",
    "assets/characters/heads/blondeCurly/whiteRight.png",
  );
  scene.load.image(
    "character-head-human-white-blonde-curly-left",
    "assets/characters/heads/blondeCurly/whiteLeft.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-curly-front",
    "assets/characters/heads/blondeCurly/blackFront.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-curly-back",
    "assets/characters/heads/blondeCurly/blackBack.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-curly-right",
    "assets/characters/heads/blondeCurly/blackRight.png",
  );
  scene.load.image(
    "character-head-human-black-blonde-curly-left",
    "assets/characters/heads/blondeCurly/blackLeft.png",
  );

  //BODY
  //Green Tunic
  scene.load.image(
    "character-body-human-green-tunic-front",
    "assets/characters/bodies/greenTunic/whiteFront.png",
  );
  scene.load.image(
    "character-body-human-green-tunic-back",
    "assets/characters/bodies/greenTunic/whiteBack.png",
  );
  scene.load.image(
    "character-body-human-green-tunic-right",
    "assets/characters/bodies/greenTunic/whiteRight.png",
  );
  scene.load.image(
    "character-body-human-green-tunic-left",
    "assets/characters/bodies/greenTunic/whiteLeft.png",
  );

  //CAPE
  //Red
  scene.load.image(
    "character-cape-human-white-red",
    "assets/characters/capes/redCape/whole.png",
  );
  scene.load.image(
    "character-cape-human-white-red-top",
    "assets/characters/capes/redCape/top.png",
  );
  scene.load.image(
    "character-cape-human-white-red-bottom",
    "assets/characters/capes/redCape/bottom.png",
  );
  scene.load.image(
    "character-cape-human-white-red-back",
    "assets/characters/capes/redCape/back.png",
  );
  scene.load.image(
    "character-cape-human-white-red-right",
    "assets/characters/capes/redCape/right.png",
  );
  scene.load.image(
    "character-cape-human-white-red-left",
    "assets/characters/capes/redCape/left.png",
  );
  // EQUIPMENT
  scene.load.image(
    "character-equipment-sword",
    "assets/characters/equipments/sword.png",
  );
}
